### ISSUE TITLE
update to use node16

### ISSUE THREAD

**Issue by adikari** [rrainn/dynamodb-action#6]
github is deprecating node12. Can we update the action to node16 pls.

![image](https://user-images.githubusercontent.com/1757714/197140079-c3070f2a-b769-42b3-b7ab-2540b85479ff.png)

**Comment by fishcharlie** [comment]
@adikari Just published v3.0.0 which should take care of this. Please test it and let me know if you run into any problems 😃

**Comment by adikari** [comment]
@fishcharlie it's looking good. thanks for updating so promptly :)
