### ISSUE TITLE
Allow setting the image version

### ISSUE THREAD

**Issue by guisehn** [rrainn/dynamodb-action#8]
Amazon recently released `amazon/dynamodb-local` version `2.0.0` with breaking changes.

One breaking change I noticed and that broke our CI, is that the `access_key_id` can no longer contain hyphens or underscores.

Currently, `rrainn/dynamodb-action` always fetches the latest version of the image. It would be nice to have a way to determine the version of the image to ensure the CI doesn't break, and fall back to `latest` if not defined.

**Comment by guisehn** [comment]
I have opened a pull request adding that: https://github.com/rrainn/dynamodb-action/pull/7

**Comment by danishi** [comment]
@guisehn 
This issue was very helpful to me. thank you :smile:

**Comment by fishcharlie** [comment]
Fixed in #7
